# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05bf77e7c31982d70904272041e0843ab80b2f025574a7245c0a0cf3217c70bdb7cc5d44e15cb47c9a4ce53dafe80fa959812f112560a2ab58b6deb63859536c

test:
  secret_key_base: e6c512e55802eef9bf047242b8c76e12ede48c159192770f44981de36e370082cbc773e4ac2452ecf798759828d844e5246b2e298508025a9e108c391af8c59a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
